### ISSUE TITLE
3D Reconstruction step

### ISSUE THREAD

**Issue by KartikaAhuja26** [MultiDIC/MultiDIC#12]
Hi Dana,
I have been facing issues for the last few weeks as I am not able to get the correct displacement as I should get. I am getting the right result with step 2, i.e. I have given 2D displacement to my object, and step 2 is working fine but after 3D reconstruction displacement values that I am getting is not correct. Can you please suggest what could be possible reasons for it. 

Thank You
Kartika

**Comment by danasolav** [comment]
Hi Kartika,

Most likely there's a problem with the calibration parameters calculated in step 1.
Did you run step1p to examine the reconstruction errors of your calibration object? What error magnitudes did you get there? If they're large, you probably have a problem with the calibration object. Maybe the 3D coordinates file you're using is incorrect?

Thanks,
Dana

**Comment by KartikaAhuja26** [comment]
![reconstructionErrors](https://user-images.githubusercontent.com/47627277/70139885-7bccc680-16b9-11ea-99a1-ab9615ac9ac6.jpg)

Hi Dana,
Sorry for the delay in replying. I am attaching the screenshot for the errors. Could you please help me in finding the possible reasons for the error in the displacement value I am getting?

Thanks
Kartika

**Comment by danasolav** [comment]
These errors seem reasonable.
What kind of errors are you getting in step3? Can you share more details on your experimental setup? You can also send me some sample data by email so I can help you debug it more efficiently.
Thanks,
Dana
