### ISSUE TITLE
problem with the stitching process 

### ISSUE THREAD

**Issue by KyrieDrewWang** [MultiDIC/MultiDIC#13]
It said in the maual that if you choose to stitch, you will be asked to select the indices of the surfaces you want to stitch together. I am confused with the indices of the surfaces. I want to know what is the indices of the surfaces, and  what should I type in. Set the sample as an example, should I type in [201 202] or just the number of the surfaces.

**Comment by KyrieDrewWang** [comment]
thanks a lot!!

**Comment by danasolav** [comment]
You should type the indices of the pairs, not the indices of the cameras. For example if pair number 1 is [201 202] and pair number 2 is [202 203] you should type [1 2].
