### ISSUE TITLE
Issues with step 2

### ISSUE THREAD

**Issue by austinp0930** [MultiDIC/MultiDIC#16]
When I load my images into MATLAB the reference image gets loaded sideways at a 90 degree angle so the cylinder does not appear upright. When I open the JPEG image with Windows Photos it appears upright.

**Comment by danasolav** [comment]
When you rotate your images in windows, it only rotates their display but it does not change the properties of the file, therefore MATLAB doesn't see it as rotated. 
If you want to rotate your images properly, you can use the MATLAB function `rotateImagesAndSave`, that's included in MultiDIC. Simply type `rotateImagesAndSave` in the command window and click enter. It will ask you to select the images, select how to save them, and how to rotate them.
`
