### ISSUE TITLE
some questions about Multi DIC limitations

### ISSUE THREAD

**Issue by NataCalc** [MultiDIC/MultiDIC#17]
Dear,

We want to know about limitations of Multi DIC on speckle patterns.  Is  it necessary to create very organised speckle pattern (columns and rows xyz) to use Multi DIC? can we use Multi DIC with sprayed speckle patterns?

We are working with scapholunate ligament (wrist) with size of 10 mm (length) x 3 mm (width) and 2-5 mm (height).

Regards,
Nataliya

**Comment by danasolav** [comment]
Hi Nataliya,
The speckle pattern can be applied in any way that you wish- sprayed, painted manually, printed, etc.
You just have to make sure that the speckles are of an appropriate size for your camera setup, and that the density and coverage are eduaqate.
The calibration object, however, must have rows and columns of dots with known accurate positions.  
Thanks,
Dana

**Comment by Hustben** [comment]
Dear,
I am a Chinese student and I don't do related research before, so I find it difficult to use Multi DIC.Even I don't know how to run it.Can you give me a video detailing the process.
Thanks, waiting for your reply.
Ben
