### ISSUE TITLE
Mex compilation instructions in manual

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [MultiDIC/MultiDIC#19]
The documentation says that `installMultiDIC` 

> ...will compile all the necessary files for Ncorr and will save the Matlab MEX files in the Ncorr folder. It has to be done only the first time.

However the code only seems to add paths e.g.:

```
addpath(genpath(fullfile(mPath,'lib_MultiDIC'))); % add libraries
addpath(genpath(fullfile(mPath,'lib_ext'))); % add external library
```

**Comment by danasolav** [comment]
Thanks for that. This is fixed in the new release (v.1.1.0).
