### ISSUE TITLE
extractImagesInfo.m

### ISSUE THREAD

**Issue by engr309** [MultiDIC/MultiDIC#2]
@danasolav @amjaeger17 @Kevin-Mattheus-Moerman 
When using STEP 0: Calculate Distortion Parameters script I get the following issue referring to extractImagesInfo.m:

Unable to perform assignment because the size of the left side is 2824-by-4240-by-3 and the size of the right side is 2824-by-4240.

Error in extractImagesInfo (line 35)
    I(:,:,:,ip)=imread(images.ImageLocation{ip});

Error in STEP0_CalcDistortionParameters (line 108)
        CBimagesInfo=extractImagesInfo(folder_paths{ic});

**Comment by engr309** [comment]
Any insight into the what a root cause could be?

**Comment by danasolav** [comment]
@engr309 
Sorry, I haven't seen the issue you posted earlier. I'll look into it tomorrow. My guess is that it has to do with the image format (some formats are imported as n-by-m-by-3 RGB and some -by-4 or by-1) Can you let me know what kind of images you are using? Or even better, send me one for example.

**Comment by danasolav** [comment]
The problem is now solved.
