### ISSUE TITLE
Axes Orientation Question

### ISSUE THREAD

**Issue by anikak14** [MultiDIC/MultiDIC#21]
Hi Dana, 

I was wondering if there is a way to set the orientations of the coordinate axes directions? Right now I'm looking for some indentation data but the direction I am looking at is split between the x and y axis in the plots. It would be great if I could somehow set it the axes directions so that the indentation is measured mainly in 1 direction. 

Does this make sense?

Thanks in advance!
Anika

**Comment by danasolav** [comment]
Hi Anika,

The coordinate system axes are determined according to the calibration
object that you create and use (in Step 1). If you want the axes to be
rotated relative to what they are right now, you can either physically
rotate the calibration object in the measurement volume (if possible) or
change the coordinates of the dots in your calibration object input file.
Could you share a bit more details (and/or photos) of your test, including
the calibration object and the speckled indented object? That would help to
better understand what you mean by the indentation direction (is that the
direction the indenter is moving?) and what the axes currently look like.
You can send me directly to danask@mit.edu.

Thanks,
Dana
