### ISSUE TITLE
STEP1_CalcDLTparameters

### ISSUE THREAD

**Issue by jiaming222** [MultiDIC/MultiDIC#24]
![16118152101273874689211706386](https://user-images.githubusercontent.com/78129826/106098952-e02bce80-6174-11eb-8de1-07542d8c88fe.jpg)
Is this error occur because of the images are not detected by multidic?

**Comment by jiaming222** [comment]
![16118153589147263900397822768370](https://user-images.githubusercontent.com/78129826/106099204-40227500-6175-11eb-8a94-d696be484c2f.jpg)
These are the images used for stereo calibration object.
Can someone help me to solve the issue?

**Comment by danasolav** [comment]
It has nothing to do with the images, only with the image file names. This line in the code tries to extract the camera number from the file name. You have to make sure you name your image files according to the convention explained in the instruction manual. Can you share here how you named your image files?

**Comment by jiaming222** [comment]
![16118984444842625550809344137685](https://user-images.githubusercontent.com/78129826/106235906-ae7b3c00-6236-11eb-9672-dcd0ee3c0ede.jpg)

**Comment by danasolav** [comment]
Can you post here what does the variable imagePaths contain after you select the images?

**Comment by jiaming222** [comment]
I had solved this error by changing the file name.
