### ISSUE TITLE
Error using importdata. 

### ISSUE THREAD

**Issue by jiaming222** [MultiDIC/MultiDIC#25]
![16120644707857576063196410409272](https://user-images.githubusercontent.com/78129826/106373919-3be69980-63b9-11eb-8d08-0f72b3951a6b.jpg)
Where can find the importdata file?
Or can someone share it?

**Comment by danasolav** [comment]
Did you add all the folders and subfolders to the Matlab path, or used the "installMultiDIC" function? It looks like you simply don't have the folder containing the icons in your Matlab path.

**Comment by jiaming222** [comment]
I had added all folders and subfolders but it still with these errors.

**Comment by jiaming222** [comment]
It had worked now.
