### ISSUE TITLE
Error during running CalcDistortionParameters step

### ISSUE THREAD

**Issue by snehamoymtu** [MultiDIC/MultiDIC#26]
![image](https://user-images.githubusercontent.com/47432372/110535520-60d3d800-80ee-11eb-8134-dd8d5f612033.png)

Can anyone please let me know why I am getting this error?

**Comment by danasolav** [comment]
It looks like you selected "repeated analysis", which means you should already have camera parameters results file. However, your camaraCBparameters file is empty. If this is the first time you run it, you should select "New analysis". If you ran it successfully in the past and saved the results, you should check why is your file empty.

**Comment by snehamoymtu** [comment]
Thanks. It works.
