### ISSUE TITLE
step3

### ISSUE THREAD

**Issue by msk123456** [MultiDIC/MultiDIC#27]
Hi:
I tried to run your DIC code based on Matlab using your sample data and it got warning in step3。

warning：Problem zipping [1] to [2] . Continuing without zipping 

An undefined function or variable is found by looking at the function:'patchPathAngles'.

The result of 3D reconstruction is no  stitches.

I hope I can get your help?

Yours,
Sk Ma

**Comment by danasolav** [comment]
Hi,

The sample data includes only 2 cameras (1 pair) which results in 1 surface, therefore you cannot stitch it to anything.
When you have your own data with more than 1 stereo pair you can try stitching, but this is not mandatory. You can always skip the stitching and continue to Step 4 to process the results.
I will add a clarification to emphasize that.

Thanks,
Dana

**Comment by msk123456** [comment]
Hi，

I analyzed two 2DDIC results based on the samples you provided. During the stitching process, the overlapping part could be eliminated, but there would be a gap in the middle, which did not become a whole.

Could you please provide the code of "patchPathAngles" function in"[A]=patchPathAngles(F1,V1,ind1,isClosedLoop); "

Yours,
Sk Ma

**Comment by danasolav** [comment]
I have added the missing function "patchPathAngles" to the library (it's under MultiDIC/lib_ext/GIBBON/lib/).
Please let me know if the issue has been resolved after that.
