### ISSUE TITLE
step3

### ISSUE THREAD

**Issue by msk123456** [MultiDIC/MultiDIC#28]
Hi，

I analyzed two 2DDIC results based on the samples you provided. During the stitching process, the overlapping part could be eliminated, but there would be a gap in the middle, which did not become a whole.

Could you please provide the code of "patchPathAngles()" function in"[A]=patchPathAngles(F1,V1,ind1,isClosedLoop); "

Thanks,
Sk Ma

**Comment by danasolav** [comment]
I have added the missing function "patchPathAngles" to the library (it's under MultiDIC/lib_ext/GIBBON/lib/).
Please let me know if the issue has been resolved after that.

**Comment by msk123456** [comment]
Hi, There is no code for the &quot;edGenormal&quot; function in the new &quot;patchPathangles&quot; function. Can you provide it again? Thanks Sk Ma------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 晚上8:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MultiDIC/MultiDIC] step3 (#28)

**Comment by danasolav** [comment]
Your message is not readable.
The function is here, you can either get it by pulling the changes or download it and add it to your library:
![image](https://user-images.githubusercontent.com/30727421/124617655-1d436d80-de45-11eb-8140-4e0a4ad6b5be.png)

**Comment by msk123456** [comment]
Hi The &quot;edgeNormal&quot; function is not implemented. Can you provide an implementation of the following &quot;edgeNormal&quot; function. Thanks Sk Ma------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 晚上10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MultiDIC/MultiDIC] step3 (#28)

**Comment by danasolav** [comment]
This is how I see your message. Can you make it clearer?
![image](https://user-images.githubusercontent.com/30727421/124619574-c2ab1100-de46-11eb-948f-7bfc857205dd.png)

**Comment by danasolav** [comment]
I've added the functions edgeNormal and vecnormalize that were missing. Let me know if that helped.

**Comment by msk123456** [comment]
I'm sorry. Because the message is not clear when I reply with my mobile phone, I will inform you of the result after the test

**Comment by msk123456** [comment]
Thank you very much for your help. It has been running normally.
