### ISSUE TITLE
plotting results on original images

### ISSUE THREAD

**Issue by takmiyamott** [MultiDIC/MultiDIC#29]
Hi Dana,

Thank you for providing this great code!

I want to plot (or overlay) my results on original images, like in the following figure (https://github.com/MultiDIC/MultiDIC/blob/master/docs/img/indentation_204_205_DispMgn_onImages.gif).
I guessed that I could acheive it by using the file plot3DmeasuresOn2Dimages.m, is that right?

I ran the script and selected 2D pair result structure and 3D pair structure.
But some error occured.
It said that:

> Reference to non-existent field 'DIC3DpairResults'.
> 
> Error in plot3DmeasuresOn2Dimages (line 16)
>         DIC3DpairResults=DIC3DpairResults.DIC3DpairResults;

How can I solve this error?
My MATLAB version is 2017b and analysis from step1 to step4 seems ok.

Thanks

**Comment by danasolav** [comment]
Hi,
Try using the code in DIC3DPP_faceMeasure_onImages_n_n.m instead of this function.
Let me know if there's anything else I can help with.
Thanks,
Dana

**Comment by takmiyamott** [comment]
Dana,
Thank you for your kindness and telling me the alternative way.
How should I specify the arguments in those functions ? 
 anim8_DIC3DPP_faceMeasure_onImages_n_n(DIC3DPPresults,pairIndex,faceMeasureString,varargin)

I guess I should put the path to the DIC3DPPresults file for the first argument.
How about the following three arguments ?

Thanks,
Tk

**Comment by danasolav** [comment]
DIC3DPPresults is the results file from step 4 (you should load it into the workspace).
pairIndex is the pair index number (if you have only 1 pair than that would be 1.
faceMeasureString is a string with the results you want to plot. The options are:
'DispMgn','DispX','DispY','DispZ','J','Lamda1','Lamda2','Epc1','Epc2','epc1','epc2','Emgn','emgn','eeq','EShearMax','eShearMax'.

**Comment by danasolav** [comment]
I fixed the original function you asked about. You may try it again.

**Comment by takmiyamott** [comment]
Dana,
Thanks for the reply and update of the original function.
It worked perfectly!
