### ISSUE TITLE
step3

### ISSUE THREAD

**Issue by zhoug15** [MultiDIC/MultiDIC#3]
Hi:
I tried to run your DIC code based on Matlab using your sample data and it got error in step3 when I load DLT files generated in step1.
 
STEP3_3Dreconstruction (line 23)
    DIC2D{ip}=DIC2D{ip}.DIC2DpairResults;

It seems there isnt a DIC2DpairPesults in DLTstruct_cam_201?
Yours,
Joe

**Comment by danasolav** [comment]
Hi Joe,
This line requires the results from STEP2. It won't work if you try to load only the DLT files from STEP1.
STEP3 requires the results of both STEP1 (DLT calibration) and STEP2 (DIC speckle matching). Do you have both? Maybe you selected them in the wrong order (the upper bar of the browsing window contains the instructions regarding which files/folders to select).
Let me know if it solved the problem or if there's any other thing I can help with.
Best,
Dana

**Comment by zhoug15** [comment]
Hi Dana:
It still got error at the same position. I will tell you what I did.
1.run step3
2.add ROIMask_C_201_C_202.mat generated in step2
3.done
And it got error "non-existence field 'DIC2DpairResults'". It also got error if I load DLTstruct file or load them both. 
In ROIMask, there is only a 3280*2464 ROIMask mat and in DLTstruct file, there are indCam, columns, imageCentroids, DLTparams and C3Dtrue. Is my file generated in step1 and step2 all right? 
Yours,
Joe

**Comment by danasolav** [comment]
Hi Joe,
It sounds like you didn't complete step2. The ROI is just the beginning of step2, and it's not the results file that you need to import in step3. If you finish step2 correctly, you will have a DIC2DpairResults structure saved.
In step2, after selecting the ROI do you go through all the DIC steps in Ncorr? You should follow section 4.5 in the instruction manual and make sure you complete all the steps.

**Comment by vc0147** [comment]
Hello Dana and Joe,

I have a similar problem where the file I generate from Step 2, "DIC2DpairResults" is a "non-existent field" when I run Step 3. I decided to comment out the "clearvars" statement to show that I do have the structure "DIC2DpairResults", but still, the same error pops up. I have attached what my screen looks like. Do you have any insight into why this might be happening? Thank you in advance!
![picture1](https://user-images.githubusercontent.com/48099344/53685100-2b0fe380-3ccb-11e9-9620-40cb77078181.png)

**Comment by zhoug15** [comment]
Hi:
It seems you didn't complete step2. You need to press enter in command line after you finish your ncorr analyze. If not, data in DIC2DpairResults is not complete.
Yours, Joe

**Comment by vc0147** [comment]
Hello Joe,
Thank you for your reply. It turns out I was just not loading in the structures correctly. 

Also, Dana & team, thank you for creating this program. This seems to be very well crafted and thorough. I look forward to interacting with it more.

**Comment by danasolav** [comment]
Thanks Joe and vc0147 (what's your name?). Glad you figured it out. Sorry for the late response.
