### ISSUE TITLE
Error in Step 4

### ISSUE THREAD

**Issue by Grupen** [MultiDIC/MultiDIC#32]
Hi Dana,
When running Step 4, it halts and returns the following error message: 

```
Cell contents assignment to a non-cell array object.

Error in triSurfaceDeformation (line 222)
            EShearMaxVec1{itime}(itri,:)=(1/sqrt(2))*(Epc1vec{itime}(itri,:)+Epc2vec{itime}(itri,:));

Error in STEP4_PostProcessing (line 81)
deformationStruct=triSurfaceDeformation(F,DIC3D.Points3D{1},DIC3D.Points3D);
```
I am running Matlab 2017b, and was analysing the included sample data to learn MultiDIC. Do you have any idea on how to resolve this issue? This issue also occurs when using Matlab 2021b and Ncorr compiled for 2021b. 

Best regards,
Frederik

**Comment by danasolav** [comment]
Hi Frederik,

Are you using the most current version of MultiDIC? I think this was a bug
that I fixed in the past.
Please let me know if you're still having issues with the current version,
and I'll look into it.

Thanks,
Dana

**Comment by Grupen** [comment]
Hi Dana,

To be sure, I tried downloading MultiDIC again, and reran Step 1 through 4, but the issue persists. I also tried a different dataset, but it still halts with the same error message. I tried with both Matlab 2017b and 2021b. 

Best regards,
Frederik

**Comment by danasolav** [comment]
I can't seem to replicate your issue. Please send me the data structure you generated in step3 and I'll try to see maybe it's something specific to your results.

**Comment by Grupen** [comment]
Hi Dana,

Here is the result structure from step3: [DIC3Dcombined_1Pairs.zip](https://github.com/MultiDIC/MultiDIC/files/7755111/DIC3Dcombined_1Pairs.zip) 
Your help is greatly appreciated.

Best regards,
Frederik

**Comment by danasolav** [comment]
I found the problem and fixed it. It happened because your data has some faces that disappear during the motion and my test data didn't. Please let me know if that solved the issue.

**Comment by Grupen** [comment]
I tried downloading MultiDIC again, and the issue appears to be resolved. Thank you.
