### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by zhoug15** [MultiDIC/MultiDIC#4]
Hi Dana:
Two questions:
1.Can I print the calibration rectangles on my calibration target instead of the specimen to be tested? Because my specimen is difficult to draw rectangles.
2.If I don't change the relative positons of my cameras, can I use the DLT files generated  last time?
Yours,
Joe

**Comment by danasolav** [comment]
1. Certainly. The calibration target should not be your specimen. It's a separate object.
2. Yes. If nothing is changed in the positions and settings of the cameras, you should be able to use the same DLT files.
