### ISSUE TITLE
Ncorr results

### ISSUE THREAD

**Issue by zhoug15** [MultiDIC/MultiDIC#5]
Hi Dana:
What's the format of displacements data generated in step2? I want to draw a vector diagram using displacements generated in Ncorr (because it has only u and v displacement) but can't understand how do data saved in the file.
Yours,
Joe

**Comment by danasolav** [comment]
Hi Joe,

In a 3D-DIC analysis, the 2D pixel-unit displacements generated by Ncorr cannot be used as physical displacements. The only meaningful displacements are the ones generated in step4. These one are 3D and have length units. You can access them from the structure generated in step 4, this way:
DIC3DPPresults.Disp.DispVec{t}
where t is the time frame index. The result is an array of size Np-by-3, where Np is the number of points and the 3 columns are the x-y-z coordinates, as defined by your calibration object.

Best,
Dana

**Comment by anikak14** [comment]
Hi Dana, 

As a follow-up to this question, I'm having a hard time finding out what the units for the displacement results (and other results) are? Visually, I think my results look reasonable, but I am unsure of what the units being used are. 

Thanks in advance!
-Anika

**Comment by danasolav** [comment]
Hi Anika,

The units of the 3D displacements depend on the units you used for the calibration object coordinates file. If you entered them in millimeters, the displacement results will also be in millimeters. The rest of the results (deformations and strains) are unitless, as they're all relative measures.

Best,
Dana
