### ISSUE TITLE
Write a new calibrationObjectCoordinates

### ISSUE THREAD

**Issue by marcofarolfi** [MultiDIC/MultiDIC#6]
Hi Dana,

How can i write a calibrationObjectCoordinates.mat file with the true 3D world coordinates of the calibration object? I don't understand what information should i write in [𝑥𝑦𝑧]. Can you give me an example?

Thank you in advance.
Marco

**Comment by danasolav** [comment]
Hi Marco,

Please see the details in section 3.1.1 of the instruction manual.
If you're using a cylindrical calibration object, you can use the script generate_cylindrical_calibration_object_coordinate_file.m to generate the calibrationObjectCoordinates.mat file based on the dimensions of the cylinder and the printed dots.
If you're using a different calibration object, you have to make the file yourself. The file contains an array with the 3D coordinates of all the dots on the calibration object, arranged by rows and columns, such that the size is number_of_rows x number_of_columns x 3. For example, if the variable name is calibration_coordinates, then the y coordinate of the center of the dot in the 5th row, 7th column are accessed by calibration_coordinates(5,7,2) etc.. The 3D coordinates of the dots on your calibration object have to be known with sufficient accuracy.

Let me know if you have any further questions,
Dana

**Comment by vc0147** [comment]
Hello Dana,

I was trying to test this program with a two camera setup with a flat calibration object, having written my own calibration object coordinates. However, I read in the previous issue (Issue #7) that at this moment, MultiDIC can only be calibrated using a cylindrical/semi-cylindrical object. This means that no other calibration object besides a cylinder can be utilized, correct?

Could you clarify if this is true?

Thank you very much,
Vivian

**Comment by danasolav** [comment]
Hi Vivian,
Indeed, at the moment it is only possible to perform the stereo calibration using a three-dimensional calibration object, and not a flat one. It doesn't have to be cylindrical, but it must be non-planar.
In the future, I will release an extension to the software which allows the calibration of a 2-camera system using the checkerboard target only. Will probably be ready at the end of August.
Thanks,
Dana

**Comment by shanchao0906** [comment]
Hi Dana,
I want to use the checkerboard as a stereo alignment，How to modify step 1？
Thank you very much,
Susan

**Comment by evgenabaqus** [comment]
> Hi Dana,
> I want to use the checkerboard as a stereo alignment，How to modify step 1？
> Thank you very much,
> Susan

Hi did you solve a problem with using checkerboard as a stereo alignment?

**Comment by danasolav** [comment]
At the moment the toolbox doesn't allow the usage of a checkerboard for stereo alignment, but I will soon publish a new toolbox that allows that (for use with two cameras, or one stereo pair). I will let you know as soon as it is out.

**Comment by danasolav** [comment]
@evgenabaqus, @shanchao0906, @vc0147 
Using my new toolbox [DuoDIC](https://github.com/SolavLab/DuoDIC), you can calibrate two cameras using a flat checkerboard instead of a cylindrical object. I hope you find it useful.

**Comment by evgenabaqus** [comment]
Wooow that's is great. Thanks a lot! looking forward to try it

четверг, 17 марта 2022 г. пользователь Dana Solav ***@***.***>
написал:
