### ISSUE TITLE
Issue with Step 2 

### ISSUE THREAD

**Issue by Dakini** [MultiDIC/MultiDIC#8]
I seem to have an issue with step 2. I can load in the images, but don't seems to be able to get further when it asks me to press enter on the image. It just seems to do nothing.

**Comment by danasolav** [comment]
In order to try to help you I need a few more details.
Do you get an error message in the command window? If so, please paste it here so I can estimate the source of the error.
After viewing the images, you should press enter in MATLAB command window and not on the image. Maybe that's the problem?

**Comment by GRosh11** [comment]
**In step 2, I am getting the below error:**

Index exceeds the number of array elements (1).

Error in createDICimageSet (line 52)
    imNum1=str2double(imNumCell1{2});

Error in Step2 (line 55)
[ImPaths,ImSet]=createDICimageSet(folderPaths,[]);

Could you please tell me what went wrong?

A reference image is attached as well.

![2R](https://user-images.githubusercontent.com/68351392/87589724-951d0300-c6dd-11ea-96b0-0bbd13f8e63f.jpg)

**Comment by adhiti123** [comment]
Hi 
I am getting the following error in step 2.
Could you please tell me the source of error?

**Error
Index exceeds the number of array elements (0).

Error in anim8_DIC_images (line 36)
hp1=imagesc(repmat(ImSet{1},1,1,3)); hold on

Error in Step2 (line 62)
hf1=anim8_DIC_images(ImPaths,ImSet);**

**Comment by danasolav** [comment]
> I seem to have an issue with step 2. I can load in the images, but don't seems to be able to get further when it asks me to press enter on the image. It just seems to do nothing.

I need more information to be able to help you. Are you getting any error message in the MATLAB command window? What version of MATLAB are you using? What photo format are you using? Can you explain exactly where are you getting stuck? Is it right when you get an animation figure showing the photos from both cameras? Have you tried left-clicking on the image with the mouse and nothing happened?

**Comment by danasolav** [comment]
> **In step 2, I am getting the below error:**
> 
> Index exceeds the number of array elements (1).
> 
> Error in createDICimageSet (line 52)
> imNum1=str2double(imNumCell1{2});
> 
> Error in Step2 (line 55)
> [ImPaths,ImSet]=createDICimageSet(folderPaths,[]);
> 
> Could you please tell me what went wrong?
> 
> A reference image is attached as well.
> 
> ![2R](https://user-images.githubusercontent.com/68351392/87589724-951d0300-c6dd-11ea-96b0-0bbd13f8e63f.jpg)

Did you make sure that you named the files and the folders according to the convention explained in the manual? Can you share with me the names of your folders and files (including extensions)? I suspect the problem comes from there, and I might be able to solve it.

Also, next time please open a new issue instead of commenting inside an existing issue, if the problem is not identical.

Thanks,
Dana

**Comment by danasolav** [comment]
> Hi
> I am getting the following error in step 2.
> Could you please tell me the source of error?
> 
> **Error
> Index exceeds the number of array elements (0).
> 
> Error in anim8_DIC_images (line 36)
> hp1=imagesc(repmat(ImSet{1},1,1,3)); hold on
> 
> Error in Step2 (line 62)
> hf1=anim8_DIC_images(ImPaths,ImSet);**

What file format are you using? Can you send me a sample photo?

Thanks,
Dana

**Comment by adhiti123** [comment]
> > Hi
> > I am getting the following error in step 2.
> > Could you please tell me the source of error?
> > **Error
> > Index exceeds the number of array elements (0).
> > Error in anim8_DIC_images (line 36)
> > hp1=imagesc(repmat(ImSet{1},1,1,3)); hold on
> > Error in Step2 (line 62)
> > hf1=anim8_DIC_images(ImPaths,ImSet);**
> 
> What file format are you using? Can you send me a sample photo?
> 
> Thanks,
> Dana

Thanks for your reply Dana!

The image I am using is in PNG format. I have attached the sample reference photo. 
![1_1](https://user-images.githubusercontent.com/68249975/88158076-e06a7080-cc0b-11ea-8898-19e4c75c69aa.png)

**Comment by danasolav** [comment]
> > > Hi
> > > I am getting the following error in step 2.
> > > Could you please tell me the source of error?
> > > **Error
> > > Index exceeds the number of array elements (0).
> > > Error in anim8_DIC_images (line 36)
> > > hp1=imagesc(repmat(ImSet{1},1,1,3)); hold on
> > > Error in Step2 (line 62)
> > > hf1=anim8_DIC_images(ImPaths,ImSet);**
> > 
> > 
> > What file format are you using? Can you send me a sample photo?
> > Thanks,
> > Dana
> 
> Thanks for your reply Dana!
> 
> The image I am using is in PNG format. I have attached the sample reference photo.
> I have also tried in JPG format, I am still getting the same error.
> ![1_1](https://user-images.githubusercontent.com/68249975/88158076-e06a7080-cc0b-11ea-8898-19e4c75c69aa.png)

What's the name of the file? Could you please send me (danask@mit.edu) a zipped file containing the original folders with your images with their original names? I suspect that's the origin of the problem.
