### ISSUE TITLE
Issue with Step1

### ISSUE THREAD

**Issue by BXDimmortal** [MultiDIC/MultiDIC#9]
Hi,I hava already used other calibrate method to get the DLT parameters(fx,fy,fs,cx,cy..) ,how can I use theses parameters to compute the 3D-strain of the pictures.

**Comment by danasolav** [comment]
Hi, sorry for the late reply.

The calibration parameters (fx,fy,fs,cx,cy..) are not the DLT parameters. However, you can calculated the 11 DLT parameters from the values of these parameters. Please refer to the MultiDIC IEEE access paper for the relationship between the two. After you calculate the DLT parameters, you'll have to create and save a .mat file for each camera, similar to the one that's generated in STEP1. Please see page 27 for the structure of "DLTstructCam". You'll only need the fields "indCam" and "DLTparams", you can skip the rest. Then, STEP3 should work using these mat files that you create.

Thanks,
Dana

**Comment by chandlersgk123** [comment]
hello,in step1, i meet a problem on line148:
STEP1_CalcDLTparameters (line 148)
        PtempNow=Ptemp(PtempYsortInd(1:NcCam(icount)),:);
it says : Index exceeds matrix dimension ?
what went wrong ？

**Comment by danasolav** [comment]
I haven't encountered this error before. In order to help you find the source of this error, I would need to have access to the calibration image and 3d coordinate file that you used to run it. Could you send it to me to danask@mit.edu? I'll try to debug it as soon as I get it.
Thanks,
Dana

**Comment by chandlersgk123** [comment]
Thank your reply Dana, i figured out the reseason.
your code is very helpful


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dana Solav"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月18日(星期三) 晚上11:27
收件人:&nbsp;"MultiDIC/MultiDIC"<MultiDIC@noreply.github.com&gt;;
抄送:&nbsp;"方方の土の"<329928594@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MultiDIC/MultiDIC] Issue with Step1 (#9)




I haven't encountered this error before. In order to help you find the source of this error, I would need to have access to the calibration image and 3d coordinate file that you used to run it. Could you send it to me to danask@mit.edu? I'll try to debug it as soon as I get it.
 Thanks,
 Dana

**Comment by wenjunj** [comment]
hello,in step1, the data is sample_data,  i meet a problem on line30 and line 208: 
Incorrect use  .* 
The matrix dimensions must be consistent

error: DLT11Calibration (line 30)
M(1:2:2*N-1,:)=[P3 ones(N,1) zeros(N,4) -P2(:,1).*P3];
error:  STEP1_CalcDLTparameters (line 208)
    L=DLT11Calibration(C2D,C3D{icount});

**Comment by adhiti123** [comment]
> Thank your reply Dana, i figured out the reseason. your code is very helpful
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Dana Solav"<notifications@github.com&gt;; 发送时间:&nbsp;2019年9月18日(星期三) 晚上11:27 收件人:&nbsp;"MultiDIC/MultiDIC"<MultiDIC@noreply.github.com&gt;; 抄送:&nbsp;"方方の土の"<329928594@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [MultiDIC/MultiDIC] Issue with Step1 (#9) I haven't encountered this error before. In order to help you find the source of this error, I would need to have access to the calibration image and 3d coordinate file that you used to run it. Could you send it to me to danask@mit.edu? I'll try to debug it as soon as I get it. Thanks, Dana — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hi,
I am also getting the same error.
Can you please tell me how the error got resolved?

**Comment by sherlock521** [comment]
hello,in step1, i meet a problem on line148:
STEP1_CalcDLTparameters (line 148)
PtempNow=Ptemp(PtempYsortInd(1:NcCam(icount)),:);
it says : Index exceeds matrix dimension ?
what went wrong ？
the same issues as 

> Thank your reply Dana, i figured out the reseason. your code is very helpful
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Dana Solav"<notifications@github.com&gt;; 发送时间:&nbsp;2019年9月18日(星期三) 晚上11:27 收件人:&nbsp;"MultiDIC/MultiDIC"<MultiDIC@noreply.github.com&gt;; 抄送:&nbsp;"方方の土の"<329928594@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [MultiDIC/MultiDIC] Issue with Step1 (#9) I haven't encountered this error before. In order to help you find the source of this error, I would need to have access to the calibration image and 3d coordinate file that you used to run it. Could you send it to me to danask@mit.edu? I'll try to debug it as soon as I get it. Thanks, Dana — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, I meet the same issues. Can you explain how to solve it.
cheers

**Comment by sherlock521** [comment]
> > Thank your reply Dana, i figured out the reseason. your code is very helpful
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Dana Solav"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2019年9月18日(星期三) 晚上11:27 收件人: "MultiDIC/MultiDIC"<[MultiDIC@noreply.github.com](mailto:MultiDIC@noreply.github.com)>; 抄送: "方方の土の"<[329928594@qq.com](mailto:329928594@qq.com)>;"Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [MultiDIC/MultiDIC] Issue with Step1 (#9) I haven't encountered this error before. In order to help you find the source of this error, I would need to have access to the calibration image and 3d coordinate file that you used to run it. Could you send it to me to [danask@mit.edu](mailto:danask@mit.edu)? I'll try to debug it as soon as I get it. Thanks, Dana — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> Hi,
> I am also getting the same error.
> Can you please tell me how the error got resolved?

Hi
if you solve the error, can you please help me with the same issue.

**Comment by koyakoya1** [comment]
hello,in step1. I have a question.
About 3. serect the mat file containing the true 3D world ~ in Run step1__STEP1_CalcDLTparameters in12page
How can I get matfile for my experiment environment?
Sorry for the rudimentary question.

**Comment by danasolav** [comment]
Hi koyakoya1,

If you're using a cylindrical calibration target, you can generate the
coordinates based on the diameter of the cylinder and the distances between
the rows and columns of your calibration points (on the paper), using this
script which is located in the lib_multidic
folder: generate_cylindrical_calibration_object_coordinate_file.m
Next time, can you please open a new issue with this question?

Thanks,
Dana
